name: riverpod_infinite_scroll_pagination
description: An infinite scroll pagination using Riverpod (Lazy loading pages as the user scrolls to the end of the list).
version: 1.0.3
homepage: https://github.com/hafees/riverpod_infinite_scroll
repository: https://github.com/hafees/riverpod_infinite_scroll
issue_tracker: https://github.com/hafees/riverpod_infinite_scroll/issues

topics:
  - riverpod
  - pagination
  - scrolling-pagination
  - infinite-scroll-pagination

environment:
  sdk: '>=3.4.0 <4.0.0'

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.5.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.4.0 
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
  riverpod_annotation: ^2.3.5
  test: ^1.25.5 
  riverpod_generator: ^2.4.0 
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.4

dependency_overrides:
  test_api: 0.7.0 

flutter:
